/**
 * SchemaGuard - Main library entry point
 */

const { parseSchema, parsePrisma } = require('./parser/index.js');
const { generateAllTypes, generateTypeDefs } = require('./generator/guard-builder.js');
const { init } = require('./init.js');
const { afterMigration } = require('./migrate.js');

async function generate(opts = {}) {
  const sql = require('fs').readFileSync(opts.input, 'utf-8');
  const ast = parseSchema(sql);
  const types = generateAllTypes(ast);
  
  if (opts.output) {
    require('fs').writeFileSync(opts.output, `// Generated by SchemaGuard\n${types}`);
    console.log(`✅ ${ast.length} type guard(s) → ${opts.output}`);
  }
  
  return types;
}

const { generateMock, generateAllMocks } = require('./mock.js');
module.exports = {
  parseSchema,
  parsePrisma,
  generateAllTypes,
  generateTypeDefs,
  generate,
  init,
  afterMigration,
  generateMock,
  generateAllMocks,
};
