/**
 * Interactive init flow for SchemaGuard
 * - Prompt for DB URL
 * - Validate connection
 * - Discover tables  
 * - Write config + generate
 */

const { Client } = require('pg');
const { readFileSync, writeFileSync, existsSync } = require('fs');
const { parseSql } = require('./parser/index.js');
const { generateAllTypes } = require('./generator/guard-builder.js');

async function init() {
  const readline = require('readline');
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  function ask(question) {
    return new Promise(resolve => rl.question(question, resolve));
  }

  console.log('\n╔════════════════════════════════════════╗');
  console.log('║   SchemaGuard Interactive Setup     ║');
  console.log('║   Time to value: < 1 minute        ║');
  console.log('╚════════════════════════════════════════╝\n');
  console.log('This wizard will:\n');
  console.log('  1️⃣  Connect to your PostgreSQL database');
  console.log('  2️⃣  Discover your tables');
  console.log('  3️⃣  Generate TypeScript type guards\n');

  // Step 1: DB URL
  let dbUrl = await ask('Database URL (or press Enter for POSTGRES_URL env var): ');
  if (!dbUrl) dbUrl = process.env.POSTGRES_URL;
  if (!dbUrl) {
    console.log('❌ No database URL provided');
    process.exit(1);
  }

  // Step 2: Validate connection
  console.log('\n🔗 Connecting to database...');
  const client = new Client({ connectionString: dbUrl });
  
  try {
    await client.connect();
    console.log('✅ Connected successfully');
  } catch (e) {
    console.log('❌ Connection failed:', e.message);
    process.exit(1);
  }

  // Step 3: Discover tables
  console.log('\n📋 Discovering tables...');
  let tables = [];
  try {
    const result = await client.query(`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
        AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `);
    tables = result.rows.map(r => r.table_name);
    console.log(`Found ${tables.length} table(s)`);
  } catch (e) {
    console.log('⚠️ Could not list tables, using fallback');
    tables = ['users'];
  }

  if (tables.length === 0) {
    console.log('❌ No tables found');
    await client.end();
    process.exit(1);
  }

  // Step 4: Choose tables
  console.log('\nAvailable tables:');
  tables.forEach((t, i) => console.log(`  ${i + 1}. ${t}`));
  console.log('  0. All tables');
  console.log('  a. Select all');
  console.log('  n. None\n');

  let selected = await ask('Choose tables (comma-separated numbers, "a" for all, "n" for none): ');
  
  if (!selected || selected === '0' || selected.toLowerCase() === 'a') {
    chosen = tables;
  } else if (selected.toLowerCase() === 'n') {
    console.log('❌ No tables selected');
    process.exit(1);
  } else {
    chosen = selected.split(',').map(s => {
      const n = parseInt(s.trim());
      return tables[n - 1] || s.trim();
    }).filter(t => tables.includes(t));
  }

  if (chosen.length === 0) chosen = tables;
  console.log('\n✅ Selected:', chosen.join(', '));

  await client.end();

  // Step 5: Generate CREATE TABLE SQL
  console.log('\n📄 Generating schema...');
  let createSQL = '';
  const client2 = new Client({ connectionString: dbUrl });
  await client2.connect();

  for (const table of chosen) {
    const result = await client2.query(`
      SELECT column_name, data_type, is_nullable, column_default
      FROM information_schema.columns
      WHERE table_name = $1 AND table_schema = 'public'
      ORDER BY ordinal_position
    `, [table]);

    const cols = result.rows.map(col => {
      let colDef = `  ${col.column_name} ${col.data_type}`;
      if (col.column_default && col.column_default.includes('nextval')) {
        colDef = `  ${col.column_name} SERIAL`;
      } else if (col.is_nullable === 'NO') {
        colDef += ' NOT NULL';
      }
      return colDef;
    });

    createSQL += `CREATE TABLE ${table} (\n${cols.join(',\n')}\n);\n\n`;
  }

  await client2.end();

  // Step 6: Write config
  const config = {
    include: chosen,
    exclude: [],
    output: { format: 'esm' }
  };

  writeFileSync('.schemaguard.json', JSON.stringify(config, null, 2));
  console.log('✅ Wrote .schemaguard.json');

  // Step 7: Generate guards
  const tablesAST = parseSql(createSQL);
  let guards = generateAllTypes(tablesAST);

  writeFileSync('schema.ts', `// Generated by SchemaGuard\n${guards}`);
  console.log('✅ Wrote schema.ts');

  console.log('\n╔════════════════════════════════════════╗');
  console.log('║       🎉 Setup Complete!          ║');
  console.log('╚════════════════════════════════════════╝\n');
  console.log('Generated type guards for: ' + chosen.join(', '));
  console.log('Files created:');
  console.log('  • .schemaguard.json (config)');
  console.log('  • schema.ts (type guards)\n');
  console.log('Next steps:');
  console.log('  schemaguard generate              # regenerate');
  console.log('  npm test                        # run tests\n');

  rl.close();
}

init().catch(e => {
  console.error('Error:', e.message);
  process.exit(1);
});